[build]
  base = "apps/web"
  publish = "dist"
  command = "pnpm build"

[build.environment]
  VITE_IS_PRODUCTION = "true"
  # Railway API URL
  VITE_API_URL = "https://defigame-production.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
