[build]
  command = "pnpm build"
  publish = "dist"

[build.environment]
  VITE_IS_PRODUCTION = "true"
  VITE_API_URL = "https://api.hey.xyz"
  NEXT_PUBLIC_LENS_NETWORK = "mainnet"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_IS_PRODUCTION = "true"
  VITE_API_URL = "https://api.hey.xyz"
  NEXT_PUBLIC_LENS_NETWORK = "mainnet"
