[build]
  command = "pnpm build"
  publish = "apps/web/dist"

[build.environment]
  VITE_IS_PRODUCTION = "true"
  VITE_API_URL = "https://0xhub2-production.up.railway.app"
  NEXT_PUBLIC_LENS_NETWORK = "mainnet"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  # Force override of any cached values
  FORCE_API_URL = "https://0xhub2-production.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_IS_PRODUCTION = "true"
  VITE_API_URL = "https://0xhub2-production.up.railway.app"
  NEXT_PUBLIC_LENS_NETWORK = "mainnet"
  # Ensure production uses Railway API
  FORCE_RAILWAY_API = "true"
