[build]
  command = "pnpm build"
  publish = "apps/web/dist"

[build.environment]
  VITE_IS_PRODUCTION = "true"
  VITE_API_URL = "https://0xhub2-production.up.railway.app"
  NEXT_PUBLIC_LENS_NETWORK = "mainnet"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  # Force override of any cached values
  FORCE_API_URL = "https://0xhub2-production.up.railway.app"
  # WalletConnect configuration
  VITE_WALLETCONNECT_PROJECT_ID = "cd542acc70c2b548030f9901a52e70c8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_IS_PRODUCTION = "true"
  VITE_API_URL = "https://0xhub2-production.up.railway.app"
  NEXT_PUBLIC_LENS_NETWORK = "mainnet"
  # Ensure production uses Railway API
  FORCE_RAILWAY_API = "true"
  # WalletConnect configuration
  VITE_WALLETCONNECT_PROJECT_ID = "cd542acc70c2b548030f9901a52e70c8"

[context.deploy-preview.environment]
  VITE_IS_PRODUCTION = "false"
  VITE_API_URL = "https://0xhub2-production.up.railway.app"
  NEXT_PUBLIC_LENS_NETWORK = "mainnet"
  # WalletConnect configuration for preview deployments
  VITE_WALLETCONNECT_PROJECT_ID = "cd542acc70c2b548030f9901a52e70c8"
