[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "openssl"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  "cd apps/api && pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["cd apps/api && pnpm codegen"]

[start]
cmd = "cd apps/api && tsx src/index.ts"
