name: One Hour Cron

on:
  schedule:
    - cron: "0 * * * *" # Every one hour
  workflow_dispatch:

jobs:
  remove-expired-subscribers:
    name: Remove Expired Pro Subscribers
    runs-on: ubuntu-latest
    steps:
      - name: Remove Expired Pro Subscribers
        run: |
          curl -X GET "https://api.hey.xyz/cron/removeExpiredSubscribers?secret=${{ secrets.SHARED_SECRET }}"
